# general settings
name: DiMoSR_X4
model_type: SRModel
scale: 4
num_gpu: 3  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: MyTrainSet
    type: PairedImageDataset
    dataroot_gt: "data/train/DF2K/HR"
    dataroot_lq: "data/train/DF2K/LR_bicubic/X4"
    filename_tmpl: '{}x4'
    directory_structure: 'direct'
    io_backend:
      type: disk
    gt_size: 512
    use_hflip: True
    use_rot: True

    # data loader
    use_shuffle: True
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 30
    prefetch_mode: cuda
    pin_memory: True

  # SEE RESULTS ON EVERY TESTSET. USE LATEST (500K) CHECKPOINT FOR TESTING.
  val_1:  # Rename to val_1 instead of having it as a list
    task: SR
    name: SET5
    type: PairedImageDataset
    dataroot_gt: "data/val/Set5/HR"
    dataroot_lq: "data/val/Set5/LR_bicubic/X4"
    filename_tmpl: '{}x4'
    directory_structure: 'direct'
    io_backend:
      type: disk
  val_2:  # Second validation set
    task: SR
    name: SET14
    type: PairedImageDataset
    dataroot_gt: "data/val/Set14/HR"
    dataroot_lq: "dataval/Set14/LR_bicubic/X4"
    filename_tmpl: '{}x4'
    directory_structure: 'direct'
    io_backend:
      type: disk

  val_3:  
    task: SR
    name: URBAN100
    type: PairedImageDataset
    dataroot_gt: "data/val/Urban100/HR"
    dataroot_lq: "data/val/Urban100/LR_bicubic/X4"
    filename_tmpl: '{}x4'
    directory_structure: 'direct'
    io_backend:
      type: disk
      
  val_4:  
    task: SR
    name: B100
    type: PairedImageDataset
    dataroot_gt: "data/val/B100/HR"
    dataroot_lq: "data/val/B100/LR_bicubic/X4"
    filename_tmpl: '{}x4'
    directory_structure: 'direct'
    io_backend:
      type: disk

# network structures
network_g:
  type: DiMoSR
  num_feat: 36
  num_block: 18
  scale: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [500000]
    restart_weights: [1]
    eta_min: !!float 1e-5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  fft_opt:
    type: FFTLoss
    loss_weight: 0.05
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: True
      better: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
      better: higher
    

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: False
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500  # You can change this port if needed